# Copyright (c) 2026, Nigel and contributors
# For license information, please see license.txt

"""The Gambia Red Cross Society's real branch / district / link structure.

Generated from the society's own registration spreadsheets ("BRANCHES AND
DISTRICT AND LINK OF THE GAMBIA STRUCTURE SUPPORT VMS 2026", the West Coast
Region 2023 list and the Upper River Region link return) and kept here as a
literal so the seed has no spreadsheet dependency and a reviewer can read what
will be created before running anything.

**Shape**: region -> district -> (link name, kind, male, female). The counts are
the society's own registration figures for that link. They are seeded as a
recorded headcount on the link's Geo Node, not as volunteer records: this app
does not invent a person, and 17,889 fabricated Red Profiles would be worse
than a number that says where it came from.

Spelling is normalised (the sheets write the same district as "lower badibou",
"LOWER BADIBOU" and "Lower Badibou") and a link listed twice in one district is
kept once. Nothing else is altered; a name a branch typed is the name it keeps.

Data, never behaviour. Nothing imports this outside `vmmsx/seed/`.
"""

STRUCTURE = {
	"Upper River Region": {
		"Fuladu East": (
			("Volunteer Aid Detachment", "Community", 23, 14),
			("Gambia College Basse Annex", "School", 17, 47),
			("St George's School Link", "School", 12, 22),
			("Nasir School Link", "School", 13, 41),
			("Koba Kunda School Link", "School", 4, 40),
			("Sare Musa Home Link", "Community", 15, 12),
			("Sabi School Link", "School", 15, 40),
			("Nafugan School Link", "School", 10, 16),
			("Basse Central Link", "Community", 20, 43),
			("Taibah Islamic Institute", "School", 34, 33),
		),
		"Jimara": (
			("Numuyel School Link", "School", 20, 50),
			("Gambisara School Link", "School", 55, 80),
			("Sotuma Sare home Link", "Community", 4, 12),
			("Demba Kunda School Link", "School", 25, 47),
			("Julangel School Link", "School", 3, 19),
			("Sare Bojo School Link", "School", 1, 33),
			("Fatako Home Link", "Community", 7, 13),
		),
		"Kantora": (
			("Suduwol School Link", "School", 55, 65),
			("Koina School Link", "School", 17, 20),
			("Garawol School Link", "School", 38, 26),
			("Fatoto School Link", "School", 15, 21),
			("Global Red Cross Link", "Community", 37, 23),
			("Song Kunda School Link", "School", 17, 25),
		),
		"Sandu": (
			("Niankui School Link", "School", 7, 13),
			("Diabugu Home Link", "Community", 15, 45),
			("Darsilameh School Link", "School", 9, 26),
			("Sare Gubu School Link", "School", 11, 37),
		),
		"Tumana": (
			("Badari Home Link", "Community", 11, 15),
			("Kissi Kissi School Link", "School", 1, 11),
			("Sanunding School Link", "School", 5, 18),
			("Kulari School Link", "School", 5, 19),
			("Badari School Link", "School", 3, 19),
			("Sare Alpha Home Link", "Community", 20, 18),
			("Sare Alpha School Link", "School", 27, 20),
			("Njayel Home Link", "Community", 11, 8),
			("Dampha Kunda School Link", "School", 7, 19),
			("Dingiri School Link", "School", 10, 24),
		),
		"Wuli East": (
			("Foday Kunda School Link", "School", 10, 18),
			("Murreh Kunda Home Link", "Community", 10, 10),
			("Maka Masireh Home Link", "Community", 20, 10),
			("Baja Kunda School Link", "School", 38, 47),
			("Murreh Kunda Ahmadiyya MBCS Link", "School", 22, 29),
			("Bantunding School Link", "School", 9, 21),
		),
		"Wuli West": (
			("Nyakoi Home Link", "Community", 8, 7),
			("Nyakoi School Link", "School", 20, 30),
			("Jah Kunda School Link", "School", 5, 17),
		),
	},  # 7 districts, 46 links
	"North Bank Region": {
		"Central Badibou": (
			("Kerr Patteh UBS/SSS", "School", 85, 96),
			("Kerr Pateh LBS", "School", 82, 61),
			("Salinkenni BCS", "School", 42, 38),
			("Marie LBS", "School", 54, 43),
			("Njaba Kunda UBS/SSS", "School", 64, 76),
			("Njaba Kunda LBS", "School", 36, 48),
		),
		"Jokadou": (
			("Dassilameh BCS", "School", 38, 43),
			("Dassilameh Home Link", "Community", 32, 47),
			("Kuntaya LBS", "School", 58, 82),
			("Kuntaya BCS", "School", 41, 68),
			("Kuntaya Home Link", "Community", 79, 84),
			("Bantanding Tokulor BCS", "School", 30, 42),
			("Munyagen BCS", "School", 54, 24),
			("Bali Mandinka BCS", "School", 46, 62),
			("Chessay Majaw BCS", "School", 61, 78),
			("Kerr Amadou BCS", "School", 71, 92),
			("St' George's Tambana BCS Tambana", "School", 46, 72),
			("Karantab LBS", "School", 61, 34),
			("Madina Modum BCS", "School", 52, 50),
		),
		"Lower Badibou": (
			("Kerewan LBS", "School", 68, 73),
			("Kerewan UBS/SSS", "School", 72, 63),
			("Kerewan Nair Arabi Sc.", "Community", 36, 56),
			("Kerewan Al Manara Sc.", "Community", 42, 58),
			("Kinta Kunda LBS", "School", 49, 71),
			("Saba LBS", "School", 51, 34),
			("Saba UBS/SSS", "School", 56, 41),
			("Banni Basic Cycle", "Community", 23, 31),
			("Mbamori Kunda LBS", "School", 41, 22),
			("Kerr Ardo BCS", "School", 78, 89),
			("Njawara LBS", "School", 56, 74),
			("Pallen Amdanlie BCS", "School", 37, 62),
		),
		"Lower Nuimi": (
			("Bara Essau UBS", "School", 89, 96),
			("Bara Essau Home Link", "Community", 102, 121),
			("Essau LBS", "School", 61, 56),
			("Essau SSS", "School", 78, 88),
			("Kanuma BCS", "School", 34, 40),
			("Fass Njagga Choi Home Link", "Community", 76, 82),
			("Madin Home Link", "Community", 86, 68),
			("Ndungu Kebbeh Home Link", "Community", 41, 34),
			("Ndofan BCS", "School", 28, 39),
			("Sajuka LBS", "School", 47, 42),
			("Madina Sering Mass UBS/SSS", "School", 68, 93),
			("St' Mathew BCS", "School", 31, 50),
			("Sami Essau LBS", "School", 58, 41),
			("St'Michael's UBS/SSS", "School", 32, 53),
			("Mbulum UBS/SSS", "School", 41, 56),
			("Kerr Sanyang BCS", "School", 29, 48),
			("Fass Njagga UBS/SSS", "School", 52, 68),
			("St'Vincent De Poul BCS", "School", 44, 62),
		),
		"Sabach Sanjal": (
			("Ngayen Sanjal UB/SSS", "School", 60, 48),
			("Ngayen Sanjal UBS", "School", 52, 64),
			("Sinchu Njabo UB/SSS", "School", 43, 69),
			("Bassik LBS", "School", 36, 51),
			("Kumbija LBS", "School", 49, 43),
			("Mbapu LBS", "School", 24, 35),
			("Dibba Kunda LBS", "School", 46, 31),
			("Dafa LBS", "School", 44, 32),
			("Sara Kunda Home Link", "Community", 53, 27),
		),
		"Upper Badibou": (
			("Farafinne Central", "Community", 134, 86),
			("Farafenni SSS", "School", 94, 85),
			("Farafinne Upper Basic", "Community", 48, 73),
			("Yallal Tankonjal", "Community", 42, 63),
			("Illiasa LBS", "School", 38, 76),
			("Illiasa UBS/SSS", "School", 82, 52),
			("Noo Kunda", "Community", 48, 37),
		),
		"Upper Nuimi": (
			("Albreda Home Link", "Community", 86, 73),
			("Sittanunku Home Link", "Community", 92, 68),
			("Bakalarr Home Link", "Community", 67, 51),
			("Kerr Cherno Home Link", "Community", 42, 59),
			("Prince BCS", "School", 51, 75),
			("Kerr Cherno UB/SSS", "School", 59, 72),
			("Bakalarr UB/SSS", "School", 50, 38),
			("Pakau LBS", "School", 32, 44),
			("Albreda UB/SSS", "School", 68, 62),
			("Sittanunku UB/SSS", "School", 75, 82),
		),
	},  # 7 districts, 75 links
	"Lower River Region": {
		"Kiang Central": (("Keneba", "Community", 0, 0),),
	},  # 1 districts, 1 links
	"West Coast Region": {
		"Foni Bondali": (
			("Mayork Home Link", "Community", 15, 25),
			("Mayork UBS/SSS", "School", 25, 47),
			("Mayork LBS Link", "School", 20, 30),
			("Bondali BCS Link", "School", 19, 13),
			("Bulleghat BCS Link", "School", 12, 25),
			("Bambara LBS Link", "School", 18, 30),
			("Bissary LBS Link", "School", 12, 16),
			("FassChamen LBS Link", "School", 19, 27),
			("Catherina Melon LBS", "School", 11, 14),
		),
		"Foni Jarrol": (
			("Sintet Home Link", "Community", 7, 19),
			("Sintet School Link", "School", 12, 26),
			("Kampassa School Link", "School", 18, 28),
			("Mangana Cantel Link", "Community", 16, 24),
			("Wassadou School Link", "School", 11, 27),
			("Wassadou Home Link", "Community", 9, 16),
			("Jorng Cantel Link", "Community", 16, 25),
			("Kalagi School Link", "School", 24, 48),
			("Kalagi Home Link", "Community", 13, 24),
			("FJSS Cantel Link", "Community", 22, 14),
			("FJSV Cantel Link", "Community", 27, 30),
		),
		"Kombo Central": (
			("Presentaion Of Mary Basic Cycle School", "School", 20, 8),
			("Jamisa U & SSS", "School", 49, 9),
			("Mahaad SSS", "School", 0, 0),
			("Brikama U & SSS", "School", 64, 19),
			("Kabafita U & SSS", "School", 70, 15),
			("Mansa Colley Bojang U & SSS", "School", 0, 0),
			("EC Arche Noah", "School", 0, 0),
			("Bottrop Techn. U & SSS", "School", 60, 21),
			("Penyem U & SSS", "School", 38, 16),
			("Brikama Central Home Red Cross Link", "Community", 58, 47),
			("Gidda - Darsilameh Home Red Cross Link", "Community", 51, 27),
			("Bafuloto Home Red Cross Link", "Community", 13, 25),
			("Penyem Home Red Cross Link", "Community", 29, 23),
			("Kitty Home Red Cross Link", "Community", 36, 20),
			("Madina Nema - Su Home Red Cross Link", "Community", 31, 9),
			("Seyone Home Red Cross Link", "Community", 25, 11),
			("Marakissa Home Red Cross Link", "Community", 8, 18),
			("Manduar Home Red Cross Link", "Community", 27, 13),
			("Brikama Nema Home Red Cross Link", "Community", 20, 11),
		),
		"Kombo East": (
			("Giboro School link", "School", 7, 24),
			("Basori Home Link", "Community", 5, 16),
			("Tubakuta Home Link", "Community", 8, 22),
			("Mandinaba Home Link", "Community", 8, 27),
			("Kuloro UBS &SSS Link", "School", 10, 35),
			("Kuloro Primary School Link", "School", 13, 17),
			("Kuloro Home Link", "Community", 15, 25),
			("Pirang Home Link", "Community", 14, 27),
			("Pirang Primary School Link", "School", 10, 25),
			("Pirang Agricultural UBS &SSS Link", "School", 11, 30),
			("Faraba Home Link", "Community", 13, 25),
			("Faraba Banta Basic Cycle School Link", "School", 11, 21),
			("Kafuta Home Link", "Community", 16, 28),
			("Kafuta UBS & SSS Link", "School", 15, 35),
			("Sohm Home Link", "Community", 5, 17),
			("Sohm Primary School Link", "School", 15, 30),
			("Tumani Tenda School Link", "School", 6, 12),
		),
		"Kombo North": (
			("Banjulinding Home Red Cross Link", "Community", 12, 20),
			("Bijilo Ward Home Red Cross Link", "Community", 19, 20),
			("Brufut Home Red Cross Link", "Community", 25, 44),
			("Brusubi Home Red Cross Link", "Community", 33, 64),
			("Busumbala Home Red Cross Link", "Community", 15, 25),
			("Jabang Home Red Cross Link", "Community", 33, 68),
			("Kombo Kerewan Home Red Cross Link", "Community", 29, 38),
			("Kunkujang Keitaya Home Red Cross Link", "Community", 24, 51),
			("Lamin Home Red Cross Link", "Community", 42, 77),
			("Madiana Home Red Cross Link", "Community", 10, 26),
			("Makuga Home Red Cross Link", "Community", 15, 26),
			("Mandinary Home Red Cross Link", "Community", 9, 26),
			("Mariama Kunda Home Red Cross Link", "Community", 15, 30),
			("Nema Kunku Home Red Cross Link", "Community", 15, 62),
			("Old Yundum Home Red Cross Link", "Community", 15, 80),
			("Sinchu Home Red Cross Link", "Community", 13, 22),
			("Sinchu Alagie Home Red Cross Link", "Community", 15, 54),
			("Sinchu Sorrie Home Red Cross Link", "Community", 17, 46),
			("Sukuta Home Red Cross Link", "Community", 128, 139),
			("Wellingara Home Red Cross Link", "Community", 14, 31),
			("Yundum Barracks Home Red Cross Link", "Community", 13, 23),
			("Banjulinding UBS/SSS Red Cross Link", "School", 7, 27),
			("Nema Kunku UBS/SSS Red Cross Link", "School", 6, 58),
			("Babylon Comprehensive School Red Cross Link", "School", 59, 10),
			("Brufut UBS/SSS Red Cross Link", "School", 18, 27),
			("John Pickering Comprehensive SSS Red Cross Link", "School", 16, 24),
			("Kombo Kerewan SSS Red Cross Link", "School", 20, 30),
			("Nemasu SSS Red Cross Link", "School", 14, 22),
			("New Yundum Academy SSS Red Cross Link", "School", 15, 24),
			("As-Salam SSS Red Cross Link", "School", 14, 21),
			("Ousman Bun Affan School Red Cross Link", "School", 12, 18),
			("Masroor SSS Red Cross Link", "School", 15, 25),
			("Model UUBS/SSS Red Cross Link", "School", 18, 29),
			("Muslim UBS/SSS Red Cross Link", "School", 20, 32),
			("Old Yundum UBS/SSS Red Cross Link", "School", 17, 26),
			("Kombo Kerewan School Red Cross Link", "School", 14, 21),
			("Marie Beneth Skill Training Center Red Cross Link", "School", 10, 20),
			("Maladah UBS/SSS Red Cross Link", "School", 15, 22),
			("Kunkujang Keitaya UBS Red Cross Link", "School", 13, 20),
			("ScanAid UBS/SSS Red Cross Link", "School", 16, 25),
			("Brusubi UBS/SSS Red Cross Link", "School", 22, 33),
			("Alieu Badara Memorial School Red Cross Link", "School", 13, 19),
			("Sukuta UBS/SSS Red Cross Link", "School", 14, 22),
			("Da Vince School Red Cross Link", "School", 11, 17),
			("St Peter's JSS/SSS Red Cross Link", "School", 25, 40),
			("Yunus English School Red Cross Link", "School", 12, 18),
			("Jabang School Red Cross Link", "School", 16, 25),
			("Lamin Daranka School Red Cross Link", "School", 15, 23),
			("Sinchu Baliya UBS Red Cross Link", "School", 12, 18),
			("Excellence Preparatory School Red Cross Link", "School", 9, 18),
			("Yundum Barracks School Red Cross Link", "School", 20, 31),
		),
		"Kombo South": (
			("Jambur Red Cross Home Link", "Community", 16, 36),
			("Batokunku Lower Basic School Link", "School", 4, 27),
			("Nyofelleh School Link", "School", 9, 25),
			("Sinchu Wurry Home Red Cross Link", "Community", 6, 16),
			("Jambur School Link", "School", 3, 50),
			("Batokunku Home Red Cross Link", "Community", 11, 23),
			("Sambuyang Home Red Cross Link", "Community", 30, 50),
			("Mingdaw School Link", "School", 31, 40),
			("Sanyang Home Red Cross Link", "Community", 50, 70),
			("Farato Home Red Cross Link", "Community", 15, 43),
			("Mamuda Home Red Cross Link", "Community", 5, 30),
			("Jambanjelly Home Red Cross Link", "Community", 20, 48),
			("Jambanjelly School Link", "School", 14, 29),
			("Sifoe Upper and Senior Secondary School Link", "School", 8, 28),
			("Nyofelleh Home Red Cross Link", "School", 13, 39),
			("Sifoe Home Red Cross Link", "Community", 11, 15),
			("Farato Bojang Kunda School Link", "School", 30, 46),
			("Kartong Home Red Cross Link", "Community", 13, 14),
			("Seven Days Adventures (S.D.A) School Link", "School", 3, 32),
			("Xavier School Link", "School", 7, 15),
			("Gunjur Khalid Bun Walid School Link", "School", 10, 35),
			("Tujereng Home Red Cross Link", "Community", 25, 40),
			("Yalding School Link", "School", 4, 32),
			("Saint Francis School Link", "School", 10, 60),
			("Tanji Home Red Cross Link", "Community", 25, 65),
			("Sambuyang Scool Link", "School", 1, 12),
			("Gambia Partners School Link", "School", 11, 26),
			("Sotokoi Daru School Link", "School", 8, 25),
			("Saint Martin's School Link", "School", 6, 17),
			("Tanji Upper Basic and Senior Secondary School", "School", 15, 35),
			("Saint Vincent De Paul School Link", "School", 6, 17),
			("Tujereng UBS and Senior Secondary School", "School", 13, 36),
		),
	},  # 6 districts, 139 links
	"Kanifing Municipal": {
		"Bakau": (("Bakau Home Red Cross Link", "Community", 41, 32),),
		"Jeshwang": (("SK Central Red Cross Link", "Community", 32, 71),),
		"Kanifing Municipality": (
			("Abuko Home Red Cross Link", "Community", 33, 63),
			("Tallinding Home Red Cross Link", "Community", 40, 32),
			("LK Sabiji Home Red Cross Link", "Community", 17, 53),
			("Bakoteh Home Red Cross Link", "Community", 25, 63),
			("Kotu Home Red Cross Link", "Community", 23, 35),
			("Ebo Town Home Red Cross Link", "Community", 17, 21),
			("Old Jeshwang Red Cross Link", "Community", 26, 52),
			("VAD Red Cross Link", "Community", 54, 42),
			("Charles Jaw Memorial Senior & Upper Basic School", "School", 43, 61),
			("Nusrat Sen. Sec. School", "School", 52, 79),
			("Bakoteh Senior & Upper Basic School", "School", 22, 52),
			("Future Generation Sen. Sec. School", "School", 36, 52),
			("Kotu Senior & Upper Basic School", "School", 67, 53),
			("Sheikh Mass Kah Sen. Sec. School", "School", 37, 72),
			("Daddy Jobe Sen. Sec. School", "School", 24, 65),
			("Charles Fowlis Sen. Sec. School", "School", 41, 62),
			("Kanifing East Sen. Sec. School", "School", 54, 64),
			("Aji Sukai Ndateh Sen. Sec. School", "School", 53, 15),
			("Methodist Academy Sen. Sec. School", "School", 18, 43),
			("Kairaba Sen. Sec. School", "School", 27, 29),
			("Ndow's Comprehensive Sen. Sec. School", "School", 23, 37),
			("Latrikunda Sabiji Sen. Sec. School", "School", 34, 42),
			("Abuko Upper Basic School", "School", 48, 0),
			("St Charles Lwanga Lower & Upper Basic School", "School", 10, 27),
			("Latrikunda Sabiji Upper School", "School", 32, 53),
			("St Therese's Lower & Upper Basic School", "School", 51, 72),
			("Latrikunda (LK) UBS School", "School", 25, 46),
			("Tallinding Upper Basic School", "School", 37, 42),
			("ABC Lower & Upper Basic School", "School", 25, 51),
			("Living Children Academy LBS & UBS School", "School", 32, 47),
			("Old Jeshwang LBS & UBS School", "School", 23, 28),
			("Bakau LBS & UBS School", "School", 14, 37),
			("Bakau New Town LBS & UBS School", "School", 24, 21),
			("New Covenant LBS & UBS School", "School", 32, 0),
			("The University of the Gambia (UTG)", "Community", 67, 52),
			("Management Development Institute (MDI)", "School", 23, 51),
			("Hadigalaa College", "School", 43, 47),
			("Insight Training Centre", "Community", 36, 17),
			("Gambia Technical Training Institute (GTTI)", "School", 27, 43),
			("Abuko Arabic School", "School", 51, 68),
			("Tallinding Islamic School (Mahaad)", "School", 70, 91),
			("Tadamun Islamic School", "School", 81, 72),
			("Bundung Massaneh Islamic School", "School", 78, 53),
			("Imam Malick Islamic Institute", "School", 44, 63),
			("Alieu Bun Abi Talib (ABAT)", "Community", 71, 78),
			("Musa Bun Nusari Arabic School", "School", 64, 77),
			("Omar Bun Khattab", "Community", 59, 67),
			("Wellingara Arabic & English School", "School", 16, 58),
			("Lalo Kanteh Arabic School", "School", 45, 55),
			("Ahlul Khair Arabic School", "School", 36, 46),
		),
		"Serrekunda East": (("Fajikunda Home Red Cross Link", "Community", 32, 70),),
		"Serrekunda West": (("Manjai Home Red Cross Link", "Community", 16, 31),),
		"Sk Central": (("Bundung Home Red Cross Link", "Community", 35, 22),),
	},  # 6 districts, 55 links
	"Central River Region": {
		"Fulladu West": (("Bansang", "Community", 14, 33),),
		"Lower Fulladu": (
			("Boiram LBS/UBS", "School", 15, 50),
			("Brikamaba UBS/SSS", "School", 7, 5),
			("Brikamaba Home Link", "Community", 5, 30),
			("Sare Babou Basic Cycle School", "School", 11, 30),
			("Fula Bantang UBS/SSS", "School", 10, 30),
			("Kerewan Lower Basic School", "School", 1, 20),
			("Jakhally Home Link", "Community", 10, 18),
		),
		"Lower Saloum": (
			("Kaur Home Link", "Community", 10, 25),
			("Jimbala Basic Cycle", "Community", 10, 18),
			("Ballanghar Basic Cycle", "Community", 4, 23),
		),
		"Niamina East": (
			("Kudang UBS/SSS", "School", 11, 15),
			("Niamina UBS/SSS", "School", 4, 104),
			("Mamud Fana Basic", "Community", 7, 5),
			("Kudang Home Link", "Community", 9, 14),
		),
		"Niani": (
			("Sare Mallaw Basic Cycle School", "School", 16, 27),
			("Firdawsi UBS/SSS", "School", 11, 23),
			("Kayai Basic Cycle School", "School", 5, 34),
			("Niani UBS/SSS", "School", 12, 16),
			("Niani Sukuta", "Community", 7, 13),
			("Kuntaur Fula Kunda UBS", "School", 11, 30),
			("WaMa", "Community", 7, 18),
			("Fula Kunda LBS", "School", 36, 50),
		),
		"Nianija": (
			("Chamen UBS/SSS", "School", 21, 53),
			("Buduck LBS/UBS/SSS", "School", 7, 32),
			("Jailan Bakadagi Basic Cycle School", "School", 6, 13),
		),
		"Nianima Dankunku": (
			("Jasadi Central Link", "Community", 7, 21),
			("Dankunku", "Community", 5, 12),
			("Kerr Lyne Lower Basic School", "School", 6, 8),
			("Sey Kunda Lower Basic School 2092", "School", 19, 12),
			("Jessadi Basic Cycle School", "School", 8, 11),
			("Jakoto Lower Basic School", "School", 4, 12),
		),
		"Sami": (
			("Demba Kalley LBS", "School", 29, 39),
			("Changai LBS", "School", 12, 20),
			("Kallen Jawo LBS", "School", 15, 25),
			("Jamali Home Link", "Community", 14, 20),
			("Kibbri LBS", "School", 15, 30),
			("Kibbri Home Link", "Community", 20, 40),
			("Karantaba UBS/SSS", "School", 24, 26),
			("Laminkoto Badala LBS", "School", 21, 54),
		),
		"Upper Fuladu West": (
			("Bansang Central Link", "Community", 30, 40),
			("Bansang UBS/SSS", "School", 25, 62),
			("Bansang UBS", "School", 25, 58),
			("Bansang Lower Basic School", "School", 42, 31),
			("Sololo Basic Cycle School", "School", 32, 24),
			("Jahanka Basic Cycle School", "School", 47, 22),
			("Chargel UBS/SSS", "School", 27, 51),
			("Njoreh Basci Cycle", "Community", 11, 34),
			("Dobong Kunda Home Link", "Community", 32, 53),
			("Boraba Basic Cycle School", "School", 59, 31),
			("Jawo Kunda Home Link", "Community", 10, 40),
		),
		"Upper Saloum": (
			("Panchang UBS/SSS", "School", 6, 20),
			("Njau Basic Cycle", "Community", 17, 42),
		),
	},  # 10 districts, 53 links
}
