(function () {
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  const shifts = [{ name: 'Morning', start: '8:00 AM', end: '12:00 PM' }, { name: 'Afternoon', start: '12:00 PM', end: '4:00 PM' }, { name: 'Evening', start: '4:00 PM', end: '8:00 PM' }];
  const initial = { weekly_availability: { Monday: ['Morning', 'Afternoon'], Tuesday: ['Morning'], Wednesday: ['Afternoon'], Thursday: ['Evening'], Friday: ['Morning'], Saturday: ['Morning'], Sunday: [] }, available_on_holidays: true };
  const modal = document.getElementById('availability-modal');
  const form = document.getElementById('availability-form');
  const loading = document.getElementById('availability-loading');
  const error = document.getElementById('availability-error');
  const empty = document.getElementById('availability-empty');
  const saveButton = document.getElementById('save-availability');
  const holidays = document.getElementById('available-holidays');
  let saved = loadSaved();
  let lastFocus;
  function translate(message) { return message; }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function loadSaved() { try { const stored = localStorage.getItem('vmmsx-weekly-availability'); return stored ? normalize(JSON.parse(stored)) : clone(initial); } catch (_) { return clone(initial); } }
  function normalize(payload) { const clean = { weekly_availability: {}, available_on_holidays: !!payload.available_on_holidays }; days.forEach((day) => { const values = Array.isArray(payload.weekly_availability?.[day]) ? payload.weekly_availability[day] : []; clean.weekly_availability[day] = [...new Set(values)].filter((value) => shifts.some((shift) => shift.name === value)); }); return clean; }
  function checkbox(day, shift, mobile) { const id = `${mobile ? 'mobile-' : ''}${day}-${shift.name}`.toLowerCase(); return `<label class="shift-choice" for="${id}"><input id="${id}" type="checkbox" data-day="${day}" data-shift="${shift.name}" aria-label="${day}, ${shift.name}, ${shift.start} to ${shift.end}"><span class="availability-check" aria-hidden="true"></span>${mobile ? `<span><strong>${shift.name}</strong><small>${shift.start}–${shift.end}</small></span>` : ''}</label>`; }
  function buildSelectors() { document.getElementById('availability-grid-body').innerHTML = days.map((day) => `<tr><th scope="row">${day}</th>${shifts.map((shift) => `<td>${checkbox(day, shift, false)}</td>`).join('')}</tr>`).join(''); document.getElementById('availability-mobile').innerHTML = days.map((day) => `<fieldset><legend>${day}</legend><div>${shifts.map((shift) => checkbox(day, shift, true)).join('')}</div></fieldset>`).join(''); document.querySelectorAll('[data-day][data-shift]').forEach((box) => box.addEventListener('change', () => { document.querySelectorAll(`[data-day="${box.dataset.day}"][data-shift="${box.dataset.shift}"]`).forEach((peer) => { peer.checked = box.checked; }); updateCount(); })); }
  function fill(payload) { document.querySelectorAll('[data-day][data-shift]').forEach((box) => { box.checked = payload.weekly_availability[box.dataset.day].includes(box.dataset.shift); }); holidays.checked = payload.available_on_holidays; updateCount(); }
  function collect() { const weekly = Object.fromEntries(days.map((day) => [day, []])); document.querySelectorAll('.availability-grid [data-day][data-shift]:checked').forEach((box) => { if (!weekly[box.dataset.day].includes(box.dataset.shift)) weekly[box.dataset.day].push(box.dataset.shift); }); return normalize({ weekly_availability: weekly, available_on_holidays: holidays.checked }); }
  function updateCount() { const total = document.querySelectorAll('.availability-grid [data-day][data-shift]:checked').length; document.getElementById('selection-count').textContent = translate(`${total} ${total === 1 ? 'shift' : 'shifts'} selected`); }
  function renderSummary() { const activeDays = days.filter((day) => saved.weekly_availability[day].length); document.getElementById('current-pattern-heading').textContent = activeDays.length ? `Available across ${activeDays.length} ${activeDays.length === 1 ? 'day' : 'days'}` : 'No weekly shifts selected'; document.getElementById('availability-summary-days').innerHTML = days.map((day) => { const selected = saved.weekly_availability[day]; return `<article class="${selected.length ? '' : 'unavailable'}"><strong>${day.slice(0, 3)}</strong><span>${selected.length ? selected.join(' · ') : 'Unavailable'}</span></article>`; }).join(''); document.getElementById('holiday-summary-text').textContent = saved.available_on_holidays ? 'You are available to be contacted on public holidays.' : 'You have marked public holidays as unavailable.'; }
  function showFormState(state) { loading.hidden = state !== 'loading'; error.hidden = state !== 'error'; empty.hidden = state !== 'empty'; form.hidden = state !== 'ready'; saveButton.hidden = state === 'empty'; saveButton.disabled = state !== 'ready'; }
  function openModal() { lastFocus = document.activeElement; modal.hidden = false; document.body.classList.add('modal-open'); showFormState('loading'); setTimeout(() => { showFormState(shifts.length ? 'ready' : 'empty'); fill(saved); document.querySelector('.availability-close').focus(); }, 450); }
  function closeModal() { modal.hidden = true; document.body.classList.remove('modal-open'); document.getElementById('save-state').textContent = ''; lastFocus?.focus(); }
  function setAll(checked) { document.querySelectorAll('[data-day][data-shift]').forEach((box) => { box.checked = checked; }); updateCount(); }
  function toast(message) { const node = document.getElementById('availability-toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2600); }
  buildSelectors(); renderSummary();
  document.getElementById('edit-availability').addEventListener('click', openModal); document.querySelector('.availability-close').addEventListener('click', closeModal); document.getElementById('close-availability').addEventListener('click', closeModal);
  document.getElementById('select-all').addEventListener('click', () => setAll(true)); document.getElementById('clear-all').addEventListener('click', () => { setAll(false); holidays.checked = false; }); document.getElementById('retry-availability').addEventListener('click', () => { showFormState('loading'); setTimeout(() => showFormState('ready'), 500); });
  saveButton.addEventListener('click', () => { saveButton.disabled = true; saveButton.classList.add('saving'); saveButton.textContent = translate('Saving…'); document.getElementById('save-state').textContent = translate('Updating your existing schedule…'); setTimeout(() => { try { saved = collect(); localStorage.setItem('vmmsx-weekly-availability', JSON.stringify(saved)); renderSummary(); document.getElementById('availability-updated').textContent = 'Updated just now'; closeModal(); toast(translate('Your weekly availability has been updated.')); } catch (_) { showFormState('error'); error.querySelector('strong').textContent = translate('We could not save your availability'); error.querySelector('p').textContent = translate('Your previous schedule is unchanged. Please try again.'); } finally { saveButton.disabled = false; saveButton.classList.remove('saving'); saveButton.textContent = translate('Save availability'); } }, 700); });
  modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(); }); document.addEventListener('keydown', (event) => { if (modal.hidden) return; if (event.key === 'Escape') closeModal(); if (event.key === 'Tab') { const focusable = [...modal.querySelectorAll('button:not([disabled]),input:not([disabled])')].filter((node) => !node.closest('[hidden]')); const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } });
  if (location.hash === '#set-availability') openModal();
})();
